name: env&secret
on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
env:
    My_workflow_Env: "This is my workflow env variable"    # workflow env variable can be accessed in any job of this workflow
jobs:
    test:
        environment: testing         
        runs-on: ubuntu-latest
        env:                                              # job env variable can be accessed only in this job
            my_job_env: "This is my job env variable"
            Adress: "awesfahsdls.0asdaswa.sa34sda..as343"
            Username:  ${{ secrets.USERNAME }}   #  secrets are encrypted environment variables created in the repository settings. 
            Password:  ${{secrets.ENV_PASSWORD}} # environment secrets   
            Port: 8080
        steps:
            - name: using workflow &  job env variable ($port) 
              run: |
                echo "workflow env -> ${{env.My_workflow_Env}}"
                echo "job env -> ${{env.my_job_env}}"
                echo "address -> ${{env.Adress}}"
                echo "username -> ${{env.Username}}"
                echo "password -> ${{env.Password}}"
                echo "port -> ${{env.Port}}"

    test2:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: output info
              run: |
                echo "workflow env -> ${{env.My_workflow_Env}}"  
                echo "job env of test1 -> ${{env.my_job_env}}"  
            
            
