name: env&secret
on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
env:
    My_workflow_Env: "This is my workflow env variable"    #  1) workflow level  env variable can be accessed in any job of this workflow
jobs:
    test:                       
        environment: testing   #environment name can be used to group jobs  It can also be used to set environment secrets that are specific to that environment.       
                               #Each environment can have its own:  Secrets , Variables , Deployment protection rules ,Required reviewers , Deployment restriction
        runs-on: ubuntu-latest
        env:                                                # 2) job level  env variable can be accessed only in this job
            my_job_env: "This is my job env variable"
            Adress: "awesfahsdls.0asdaswa.sa34sda..as343"
            Username:  ${{ secrets.USERNAME }}   # a)  secrets are encrypted environment variables created in the repository settings. 
            Password:  ${{secrets.ENV_PASSWORD}} # b)  environment secrets   
            Port: 8080
        steps:
            - name: using workflow &  job env variable ($port)  & step level env
              env:                                          # 3) step level env variable can be accessed only in this step
                VERSION: 1.0
              run: |
                echo "workflow env -> ${{env.My_workflow_Env}}"
                echo "workflow env directly -> $My_workflow_Env"
                echo "job env -> ${{env.my_job_env}}"
                echo "address -> ${{env.Adress}}"
                echo "username -> ${{env.Username}}"
                echo "password -> ${{env.Password}}"
                echo $Port
                echo "step level env -> $VERSION"                      
         

    test2:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: output info
              run: |
                echo "workflow env -> ${{env.My_workflow_Env}}"   
                echo "job env of test1 -> ${{env.my_job_env}}"  
             
            
